version: "3.9"

services:
  ais-backend:
    container_name: ais-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8990:8989"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.13.1.180:5432/healthcare_app_db
      SPRING_DATASOURCE_USERNAME: healthcare_app_user
      SPRING_DATASOURCE_PASSWORD: demo
    networks:
      - aisnetwork

networks:
  aisnetwork:
    driver: bridge
